# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Mail-Postini
version:      0.07
version_from: lib/Mail/Postini.pm
installdirs:  site
requires:
    Digest::SHA1:                  2.1
    LWP::UserAgent:                2
    URI::Escape:                   3.2

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
